name: CI-CD-Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, prod ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: karan-ecs-backend
  CLUSTER_NAME: prop-ecs-cluster
  SERVICE_NAME: prop-backend-service
  CONTAINER_NAME: backend

jobs:

  # -----------------------------------------------------------
  # TEST + SCAN
  # -----------------------------------------------------------
  test_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests
        run: echo "Tests passed!"

      - name: Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: filesystem
          path: .
          ignore-unfixed: true

  # -----------------------------------------------------------
  # BUILD + PUSH IMAGE
  # -----------------------------------------------------------
  build_and_push:
    needs: test_and_scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY ./app/backend

      - name: Tag Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag $ECR_REPOSITORY:latest \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Image
        run: docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${IMAGE_TAG}

  # -----------------------------------------------------------
  # DEPLOY TO ECS â€” NO TASK DEFINITION FILE
  # -----------------------------------------------------------
  d  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Register new task definition revision
        id: taskdef
        run: |
          NEW_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}"
          TASK_DEF=$(aws ecs describe-task-definition --task-definition ecs-backend-task)
          NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | {containerDefinitions, family, executionRoleArn, networkMode, requiresCompatibilities, cpu, memory}')
          echo "$NEW_TASK_DEF" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition ecs-backend-task \
            --force-new-deployment


